# Generated by Django 5.1.7 on 2025-05-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='baker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cake_shop.baker'),
        ),
    ]
