# Generated by Django 5.1.7 on 2025-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0002_alter_cake_baker'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='baker_images/'),
        ),
    ]
